spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/justsayit;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}  # IAM 계정의 accessKey
      secret-key: ${S3_SECRET_KEY}  # IAM 계정의 secretKey
    region:
      static: ${AWS_REGION}  # 버킷의 리전
    s3:
      bucket: ${S3_BUCKET}   # 버킷 이름
    stack:
      auto: false

jwt:
  secret:
    key: ${JWT_SECRET_KEY:}
    expiration-time: ${JWT_SECRET_EXT} # 1시간

basic-profile-img:
  blue: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-blue.png
  pink: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-pink.png
  purple: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-purple.png
  yellow: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-yellow.png


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}  # IAM 계정의 accessKey
      secret-key: ${S3_SECRET_KEY}  # IAM 계정의 secretKey
    region:
      static: ${AWS_REGION}  # 버킷의 리전
    s3:
      bucket: ${S3_BUCKET}   # 버킷 이름
    stack:
      auto: false

jwt:
  secret:
    key: ${JWT_SECRET_KEY:}
    expiration-time: ${JWT_SECRET_EXT} # 1시간

basic-profile-img:
  blue: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-blue.png
  pink: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-pink.png
  purple: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-purple.png
  yellow: https://jsi-bucket.s3.ap-northeast-2.amazonaws.com/default-profile-yellow.png